name: Periodic health check

on:
  schedule:
    - cron: '3 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-22.04
    steps:
      - name: env context
        run: echo "$ENV_CONTEXT"
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
      - name: vars context
        run: echo "$VARS_CONTEXT"
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
      - name: Check production instance
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ vars.APP_URL }}
          max-attempts: 3
          retry-delay: 5s