name: Periodic health check

on:
  push:
    branches:
     - main
     - ex11_19

jobs:
  health_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check production instance
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.APP_URL }}
          max-attempts: 3
          retry-delay: 5s