name: Periodic health check

on:
  push:
    branches:
     - main

jobs:
  health_check:
    runs-on: ubunti-22.04
    steps:
      - name: Check production instance
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.APP_URL }}
          max-attempts: 3
          retry-delay: 5s